### PR TITLE
Test pyrobench again

### PR DESCRIPTION
**Pull request by simonswine**
This is a PR to experiment with pyrobench controlled by issue comments

### CODE REVIEW

**Comment by simonswine** [comment]
@pyrobench BenchmarkInflightInstanceTracker

**Comment by simonswine** [comment]
@pyrobench BenchmarkInflightInstanceTracker

**Comment by simonswine** [comment]
@pyrobench BenchmarkInflightInstanceTracker

**Comment by simonswine** [comment]
### Benchmark Report

__In progress__

3ba30e2c7b8604cdd68cd1522ce85151f307b3ce -> 1c366120a7ff617489032244476332f858bee8ed ([compare](https://github.com/grafana/hackathon-2024-08-pyrobench-dskit/compare/3ba30e2c7b8604cdd68cd1522ce85151f307b3ce...1c366120a7ff617489032244476332f858bee8ed))
<details>
<summary><tt>github.com/grafana/dskit/ring.BenchmarkInflightInstanceTracker</tt></summary>

| Resource | Base | Head | Diff % |
|----------|-----:|-----:|-------:|
</details>

**Comment by simonswine** [comment]
@pyrobench BenchmarkInflightInstanceTracker

**Comment by simonswine** [comment]
@pyrobench BenchmarkRing_Get

**Comment by simonswine** [comment]
@pyrobench BenchmarkRing_Get

**Comment by simonswine** [comment]
@pyrobench BenchmarkRing_Get

**Comment by simonswine** [comment]
@pyrobench BenchmarkRing_Get count=11 time=10x

**Comment by simonswine** [comment]
### Benchmark Report

__In progress__

3ba30e2c7b8604cdd68cd1522ce85151f307b3ce -> 1c366120a7ff617489032244476332f858bee8ed ([compare](https://github.com/grafana/hackathon-2024-08-pyrobench-dskit/compare/3ba30e2c7b8604cdd68cd1522ce85151f307b3ce...1c366120a7ff617489032244476332f858bee8ed))
<details>
<summary><tt>github.com/grafana/dskit/ring.BenchmarkInflightInstanceTracker</tt></summary>

| Resource | Base | Head | Diff % |
|----------|-----:|-----:|-------:|
</details>

**Comment by bryanhuhta** [comment]
@pyrobench BenchmarkRing_Get count=11 time=10x

**Comment by simonswine** [comment]
@pyrobench BenchmarkRing_Get count=11 time=10x

**Comment by simonswine** [comment]
@pyrobench BenchmarkInflightInstanceTracker

**Comment by simonswine** [comment]
@pyrobench BenchmarkInflightInstanceTracker xasdsa=123

**Comment by simonswine** [comment]
@pyrobench BenchmarkInflightInstanceTracker

**Comment by simonswine** [comment]
@pyrobench InstanceTracker

**Comment by simonswine** [comment]
### Benchmark Report

__In progress__

3ba30e2c7b8604cdd68cd1522ce85151f307b3ce -> 1c366120a7ff617489032244476332f858bee8ed ([compare](https://github.com/grafana/hackathon-2024-08-pyrobench-dskit/compare/3ba30e2c7b8604cdd68cd1522ce85151f307b3ce...1c366120a7ff617489032244476332f858bee8ed))
<details>
    <summary><tt>github.com/grafana/dskit/ring.BenchmarkInflightInstanceTracker</tt>(scheduled)</summary>

| Resource | Base | Head | Diff % |
|----------|-----:|-----:|-------:|
</details>

**Comment by simonswine** [comment]
### Benchmark Report

__In progress__

8fab55d9ef829e4d368ed5e2113996061bf88c5d -> b5465c5c6d9569fe75de6d6e668366777932c469 ([compare](https://github.com/grafana/hackathon-2024-08-pyrobench-dskit/compare/8fab55d9ef829e4d368ed5e2113996061bf88c5d...b5465c5c6d9569fe75de6d6e668366777932c469))
<details>
    <summary><tt>github.com/simonswine/pyrobench-testdata.BenchmarkFib10</tt>(scheduled)</summary>

| Resource | Base | Head | Diff % |
|----------|-----:|-----:|-------:|
</details>

**Comment by simonswine** [comment]
### Benchmark Report

__In progress__

8fab55d9ef829e4d368ed5e2113996061bf88c5d -> b5465c5c6d9569fe75de6d6e668366777932c469 ([compare](https://github.com/grafana/hackathon-2024-08-pyrobench-dskit/compare/8fab55d9ef829e4d368ed5e2113996061bf88c5d...b5465c5c6d9569fe75de6d6e668366777932c469))
<details>
    <summary><tt>github.com/simonswine/pyrobench-testdata.BenchmarkFib10</tt>(scheduled)</summary>

| Resource | Base | Head | Diff % |
|----------|-----:|-----:|-------:|
</details>

**Comment by simonswine** [comment]
### Benchmark Report

__In progress__

8fab55d9ef829e4d368ed5e2113996061bf88c5d -> b5465c5c6d9569fe75de6d6e668366777932c469 ([compare](https://github.com/grafana/hackathon-2024-08-pyrobench-dskit/compare/8fab55d9ef829e4d368ed5e2113996061bf88c5d...b5465c5c6d9569fe75de6d6e668366777932c469))
<details>
    <summary><tt>github.com/simonswine/pyrobench-testdata.BenchmarkFib10</tt>(scheduled)</summary>

| Resource | Base | Head | Diff % |
|----------|-----:|-----:|-------:|
</details>

**Comment by simonswine** [comment]
### Benchmark Report

__In progress__

8fab55d9ef829e4d368ed5e2113996061bf88c5d -> b5465c5c6d9569fe75de6d6e668366777932c469 ([compare](https://github.com/grafana/hackathon-2024-08-pyrobench-dskit/compare/8fab55d9ef829e4d368ed5e2113996061bf88c5d...b5465c5c6d9569fe75de6d6e668366777932c469))
<details>
    <summary><tt>github.com/simonswine/pyrobench-testdata.BenchmarkFib10</tt>(scheduled)</summary>

| Resource | Base | Head | Diff % |
|----------|-----:|-----:|-------:|
</details>

**Comment by simonswine** [comment]
### Benchmark Report

__In progress__

8fab55d9ef829e4d368ed5e2113996061bf88c5d -> b5465c5c6d9569fe75de6d6e668366777932c469 ([compare](https://github.com/grafana/hackathon-2024-08-pyrobench-dskit/compare/8fab55d9ef829e4d368ed5e2113996061bf88c5d...b5465c5c6d9569fe75de6d6e668366777932c469))
<details>
    <summary><tt>github.com/simonswine/pyrobench-testdata.BenchmarkFib10</tt>(scheduled)</summary>

| Resource | Base | Head | Diff % |
|----------|-----:|-----:|-------:|
</details>

**Comment by simonswine** [comment]
@pyrobench InstanceTracker

**Comment by simonswine** [comment]
@pyrobench Ring

**Comment by simonswine** [comment]
@pyrobench InstanceTracker xyz=123

**Comment by simonswine** [comment]
### Benchmark Report

__Finished__
no benchmarks to run
3ba30e2c7b8604cdd68cd1522ce85151f307b3ce -> 1c366120a7ff617489032244476332f858bee8ed ([compare](https://github.com/grafana/hackathon-2024-08-pyrobench-dskit/compare/3ba30e2c7b8604cdd68cd1522ce85151f307b3ce...1c366120a7ff617489032244476332f858bee8ed))

**Comment by simonswine** [comment]
### Benchmark Report

__Finished__
no benchmarks to run
3ba30e2c7b8604cdd68cd1522ce85151f307b3ce -> 1c366120a7ff617489032244476332f858bee8ed ([compare](https://github.com/grafana/hackathon-2024-08-pyrobench-dskit/compare/3ba30e2c7b8604cdd68cd1522ce85151f307b3ce...1c366120a7ff617489032244476332f858bee8ed))

**Comment by simonswine** [comment]
### Benchmark Report

```
failed to parse command line: unknown option: yzas=123
```

**Comment by simonswine** [comment]
@asdasdasc asdgvasgfasfgasdfgdsfgd

**Comment by simonswine** [comment]
@pyrobench asdgvasgfasfgasdfgdsfgd

**Pull request closed without merging**
